#running at https://sdev255g4.solnet.dev
name: school-registration

services:
  school-registration:
    container_name: school-registration
    image: node:23
    restart: unless-stopped
    working_dir: /app
    command: >
      sh -c "npm install && npm start"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - school-registration_net
    ports:
      - "8080:3000"

  school-registration_db:
    container_name: school-registration_db
    image: mongo
    restart: unless-stopped
    env_file:
      - ./env/mongo.env
    volumes:
      - ./database:/data/db
    networks:
      - school-registration_net
    ports:
      - "27019:27017"

networks:
  school-registration_net:
    driver: bridge